### ISSUE TITLE
src/ in .npmignore generates empty project

### ISSUE THREAD

**Issue by stegrams** [jacobbubu/generator-cycle-coffee-hot-reloading#1]
When I run yo and select 'Cycle Coffee Hot Reloading', just print 

```
Copying gulpfile
Copying project files
```

and exits. No files created.

Is there any reason to place `src/` entry in .npmignore in `templates` folder?

**Comment by jacobbubu** [comment]
Thank you for pointing out my fault. I have just fixed all issues I found and have made the demo run.
Please try again.

**Comment by stegrams** [comment]
There are allot of things fixed here! Thanks for sharing!
